INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('World Domination', 'Power', 100000000000000, 190225, 200225);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('World Domination', 'Power', 100000000000000, 190225, 200225);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('World Domination', 'Power', 100000000000000, 190225, 200225);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('World Domination', 'Power', 100000000000000, 190225, 200225);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('World Domination', 'Power', 100000000000000, 190225, 200225);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('World Domination', 'Power', 100000000000000, 190225, 200225);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('World Domination', 'Power', 100000000000000, 190225, 200225);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('World Domination', 'Power', 100000000000000, 190225, 200225);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('World Domination', 'Power', 100000000000000, 190225, 200225);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('World Domination', 'Power', 100000000000000, 190225, 200225);

INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);
INSERT INTO users (name, age) VALUES ("THOT", 105);

INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
